[2023-11-21T00:38:47.978+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-21T00:38:47.987+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-21T00:38:47.988+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:38:48.095+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-09 00:00:00+00:00
[2023-11-21T00:38:48.110+0000] {standard_task_runner.py:57} INFO - Started process 83 to run task
[2023-11-21T00:38:48.138+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpn0vo2_f0']
[2023-11-21T00:38:48.146+0000] {standard_task_runner.py:85} INFO - Job 114: Subtask load_data
[2023-11-21T00:38:48.222+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-09T00:00:00+00:00 [running]> on host c6d84631e1b9
[2023-11-21T00:38:48.364+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-21T00:38:52.051+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:38:52.088+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231109T000000, start_date=20231121T003847, end_date=20231121T003852
[2023-11-21T00:38:52.160+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:38:52.217+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T00:43:57.728+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-21T00:43:57.739+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-21T00:43:57.739+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:43:57.756+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-09 00:00:00+00:00
[2023-11-21T00:43:57.769+0000] {standard_task_runner.py:57} INFO - Started process 135 to run task
[2023-11-21T00:43:57.795+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpddr5w8kw']
[2023-11-21T00:43:57.802+0000] {standard_task_runner.py:85} INFO - Job 153: Subtask load_data
[2023-11-21T00:43:57.886+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-09T00:00:00+00:00 [running]> on host 51d09cf321f5
[2023-11-21T00:43:57.983+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-21T00:44:01.621+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:44:01.677+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231109T000000, start_date=20231121T004357, end_date=20231121T004401
[2023-11-21T00:44:01.782+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:44:01.857+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T01:04:25.192+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-21T01:04:25.196+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.load_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-21T01:04:25.196+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T01:04:25.202+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2023-11-09 00:00:00+00:00
[2023-11-21T01:04:25.216+0000] {standard_task_runner.py:57} INFO - Started process 303 to run task
[2023-11-21T01:04:25.222+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'load_data', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpt9d4vbn7']
[2023-11-21T01:04:25.229+0000] {standard_task_runner.py:85} INFO - Job 248: Subtask load_data
[2023-11-21T01:04:25.271+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.load_data scheduled__2023-11-09T00:00:00+00:00 [running]> on host e39dda9a9deb
[2023-11-21T01:04:25.340+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-21T01:04:28.718+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T01:04:28.742+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=load_data, execution_date=20231109T000000, start_date=20231121T010425, end_date=20231121T010428
[2023-11-21T01:04:28.815+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T01:04:28.883+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
